spring:
  application.name: task10
  datasource:
    url: jdbc:postgresql://localhost:5454/task10
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate.show_sql: false
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: WARN
