spring:
  application.name: task10
  datasource:
    url: jdbc:postgresql://localhost:5454/task10
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
#  docker.compose:
#      enabled: true
#      file: compose.yml

  jpa:
    properties.hibernate.show_sql: false
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: WARN

security:
  signing:
    key: c63a4b9c304df32b788ca2404869a51b44adaa1d253cf9f5eb5bd75b45e5aea9
    ttl: 600000
