name: CI/CD workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adoptopenjdk'

      - name: Set up kotlin
        uses: actions/setup-kotlin@v1
        with:
          kotlin-version: '1.9.25'

      - name: Installing Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Build the project with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run Static Code Analysis with Detekt
        run: ./gradlew detekt

      - name: Measure Test Coverage
        run: ./gradlew jacocoTestReport

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/