services:
  psql:
    container_name: place_events_psql
    image: postgres:14-alpine3.20
    environment:
      POSTGRES_DB: task10
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5454:5432

  task-10:
    container_name: task-10
    build:
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - psql