spring:
  application:
    name: task7

server:
  port: 8081

api:
  cbr:
    base-url: https://www.cbr.ru/scripts
    daily-rates: /XML_daily.asp/

cache:
  currencies:
    key: "currencies"
    ttl: 3600000
