spring:
  application:
    name: task5

concurrency:
  thread-pool:
    executors: 2
    schedulers: 2
  initialize:
    delay: 10m

api:
  kudago:
    base-url: https://kudago.com/public-api/v1.4
    categories: /place-categories/
    locations: /locations/