spring:
  application:
    name: task5

concurrency:
  thread-pool:
    executors: 2
    schedulers: 2
  initialize:
    delay: 10m
  completable-future:
    core-pool-size: 2
    max-pool-size: 2
    queue-capacity: 500

api:
  kudago:
    base-url: https://kudago.com/public-api/v1.4
    categories: /place-categories/
    locations: /locations/
    events: /events/
  currency:
    base-url: http://localhost:8081/currencies
    convert: /convert